### ISSUE TITLE
[fix][feature wish] mods.toml注明依赖&希望添加hp相关调整与配置

### ISSUE THREAD

**Issue by Dave-12138** [LyquidQrystal/fightorflight#5]
`/forge/src/main/resources/META-INF/mods.toml`
建议在里面加个
```toml
[[dependencies.fightorflight]]
modId = "architectury"
mandatory = true
versionRange = "[9.1.12,)"
ordering = "NONE"
side = "BOTH"
```
**feature wish**：宝可梦实体生命值与宝可梦hp的同步
同时调整宝可梦实体的生命值上限（好像只能`entity.getAttribute(Attributes.MAX_HEALTH).setBaseValue()`?）
通过配置文件调整hp到生命值的转化比例、转化结果生命值上限的下限；
宝可梦对喷溅治疗药水等对实体治疗手段的反应。
```java
        // 可能 也许 大概 这么写？
@Inject(method = "tick", at = @At("TAIL"))
public void maxHeathInject(CallbackInfo ci) {
    Pokemon pkm = getPokemon();
    PokemonEntity entity = pkm.getEntity();
    float multiplier = 0.5f;// 应该放到配置文件里，很可惜我不会（
    double min = 20;
    // 也许不该是这么个简单的正比例线性，但更好的我想不出来（
    double maxHealth = Math.floor(Math.max(multiplier * pkm.getHp(), min));
    if (entity != null && entity.isAlive()) {
        AttributeInstance attr = entity.getAttribute(Attributes.MAX_HEALTH);
        if (attr != null) {
            attr.setBaseValue(maxHealth);
        }
        if (maxHealth > min) {
            entity.setHealth(multiplier * pkm.getCurrentHealth());
        } else {
            entity.setHealth((float) (pkm.getCurrentHealth() * min / pkm.getHp()));
        }
    }
}

@Inject(method = "hurt", at = @At("TAIL"))
public void hurtInject(DamageSource source, float amount, CallbackInfoReturnable<Boolean> cir) {
    Pokemon pkm = getPokemon();
    var hp = pkm.getCurrentHealth() - amount;
    pkm.setCurrentHealth((int) hp);
}

@Override
public void heal(float healAmount) {
    Pokemon pkm = getPokemon();
    var hp = pkm.getCurrentHealth() + healAmount;
    pkm.setCurrentHealth((int) hp);
//        super.heal(healAmount); 
}
```

（_原本的生命值上限似乎是根据种族值算的，10级是20点生命上限感觉挺好，但我有点难以接受100级宝可梦只有20点生命上限，同时另一个种族不到40级又有48生命上限，数值碾压还被反杀。。。_）

**Comment by LyquidQrystal** [comment]
版本号我下次改吧，昨天本来在写携带物的增伤效果的今天看issue发现有人说11月新版本就要出来了，今天中午本来想试着能不能移植到1.21.1配合1.6的结果遇到了点问题，我现在有事碰不到电脑等会儿有空再试试。下个版本可能就等方块宝可梦1.6发布再发了。
实体生命值和hp同步考虑过，我也找过相关代码，最大生命值是差不多在初始化的时候有一个函数设置的，就是拿种族值算的，上限是请假王的，下限忘了是谁的（先排除鬼蝉，我记得不是这个），拿个弃世猴，血巨厚，雀食不合理，但回血的优先级我放的挺低的，因为算法拿不准再加上一些交互拿不准才没做的（文柚果的这种治疗物品代码应该没那么好写？）等我这几项干完再看看

**Comment by LyquidQrystal** [comment]
做完了，试了下没什么问题，文柚果治疗宝可梦同时治疗物品先不写了。新版本可能得Cobblemon 1.6发，不过你自己会编译，想试试也行。
刚刚把你写的这个issue看了一下，20血其实有可能是显示bug,我试过了，实际数值满血30多，显示20的宝可梦实体剩十来血，可以奶到20以上,可能是因为设置血量上限的时候只用了PokemonServerDelegate，客户端有时收不到吧，这个有点难修，收回再发出来显示可能会正常，不行就多试几次，不过毕竟不影响后台数据，想看血条可以直接看侧边
![2024-11-14_10 29 28](https://github.com/user-attachments/assets/69494874-82c7-483d-8156-bc2c6d5c4012)
![2024-11-14_10 29 34](https://github.com/user-attachments/assets/7a2e798a-2516-4dcd-88b9-99b1b16c2a6b)
